import Head from 'next/head'
import React from 'react'
import styles from "@/styles/Home.module.css";


const about = () => {
  return (
    <>
      <Head>
        <title>About us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/veloura.png" />
      </Head>
      <main>
        <h1 style={{textAlign:'center',fontSize:'2.5rem',fontFamily:'serif',color:'#34393C',padding:'5rem 0px'}}>About us</h1>
        <div>
          <div style={{width:'100vw',height:'100vh',backgroundColor:'#CAC7CA',display:'flex',flexWrap:'wrap',overflow:'hidden'}}>
            <div style={{width:'50vw',backgroundColor:'#E1E0DE'}}>
              <div style={{color:'#8B8386',margin:'0 auto',padding:'10rem 6rem'}}>
              <h1 style={{fontFamily:'serif',fontSize:'1.2rem',lineHeight:'3rem'}}>About us</h1>
              <p style={{fontSize:'0.9rem'}}>Welcome to Veloura – where style meets substance. Since 2024, we've been crafting distinctive garments that empower individuals, blending timeless elegance with contemporary flair. At Veloura, clients aren't just customers; they're cherished members of our family. Join us on a journey of style and innovation. Veloura isn't just clothing; it's an expression of individuality, a celebration of craftsmanship, and a commitment to making the world a more stylish place, one garment at a time.</p>
              </div>
            </div>
            <div style={{width:'50vw'}}><img style={{transform:'translate(0%,-10%)'}} src="/about.jpg" alt="" /></div>
          </div>
        </div>
        <div style={{height:'60vh',backgroundColor:'#A49F92',display:'flex',justifyContent:'center',alignItems:'center',marginBottom:'15rem'}}>
          <h1 style={{fontFamily:'serif',color:'white',fontSize:'2rem',textAlign:'center',padding:'0rem 15rem'}}>Elevating apparel with a blend of aesthetics, high performance, and innovation for a feel, fit, and look that's simply exceptional.</h1>
        </div>
      </main>
    </>
  )
}

export default about