import Head from 'next/head'
import React from 'react'
import styles from "@/styles/Home.module.css";

const cart = () => {
    return (
        <>
            <Head>
                <title>Your Cart</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/veloura.png" />
            </Head>

            <div className={styles.cartpage}>
                <h1 style={{ color: '#3A393C', lineHeight: '5rem' }}>Your Cart</h1>

                <div>
                    <div className={styles.cartitem}>
                        <div className={styles.cimg}>
                            <img src="/sqr4.jpg" alt="" />
                        </div>
                        <div className={styles.cartdtls}>
                            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                                <a href="/">Title</a>
                                <button className={styles.cross} style={{ fontSize: '1.2rem' }}><span>&#215;</span></button>
                            </div>
                            <h2 style={{ lineHeight: '0.5rem', fontSize: '0.9rem' }}>Rs. 2340.00</h2>
                            <p style={{ color: 'grey', fontSize: '0.9rem', lineHeight: '2rem' }}>Black</p>
                            <div style={{ display: 'flex', justifyContent: 'space-between', paddingTop: '1rem' }}>
                                <input style={{ width: '11vw', outline: 'none', border: '1px solid grey', padding: '5px', borderRadius: '1px' }} type="number" placeholder='Enter Quantity' min="1" max="5" />
                                <p><small>Rs. 2,000.00</small></p>
                            </div>
                        </div>
                    </div>
                    <div style={{ width: '95%', height: '1px', backgroundColor: '#80808054', margin: '0 auto', marginTop: '12px', marginBottom: '12px' }}></div>
                </div>

            </div>

            <div className={styles.checkout}>
            <div style={{display:'flex',flexDirection:'column'}}>
                <div style={{display:'flex',justifyContent:"space-between",fontSize:'0.9rem'}}><h2>Subtotal</h2>
                <span>Rs. 4580.00</span></div>
                </div>
                <small><p style={{color:'grey'}}>Taxes and <span style={{textDecoration:'underline'}}> <a href="">shipping</a> </span> calculated at checkout</p></small>
                <button style={{border:'1px solid #2E2D34',color:'white',backgroundColor:'#2E2D34',padding:'12px 0px',borderRadius:'5px',margin:'10px 0px'}}>
                    Check out
                </button>
            </div>
        </>
    )
}

export default cart