import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from "@/styles/Home.module.css";
import * as React from 'react';
import Box from '@mui/material/Box';
import Stepper from '@mui/material/Stepper';
import Step from '@mui/material/Step';
import StepLabel from '@mui/material/StepLabel';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import Dilivery from './checkout/Dilivery';
import Ordersummary from './checkout/Ordersummary';

const steps = ['Login', 'Delivery Details', 'Order Summary', 'Payment'];

export default function HorizontalLinearStepper() {
  const [activeStep, setActiveStep] = React.useState(0);
  const router = useRouter();

  const { query } = router;
  const step = query.step || 0;

  const [skipped, setSkipped] = React.useState(new Set());
  const isStepSkipped = (step) => skipped.has(step);

  return (
    <>
      <Head>
        <title>Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/veloura.png" />
      </Head>

      <main>
        <div className='px-10 py-10'>
          <Box sx={{ width: '100%' }}>
            <Stepper activeStep={step}>
              {steps.map((label, index) => {
                const stepProps = {};
                const labelProps = {};
                if (isStepSkipped(index)) {
                  stepProps.completed = false;
                }
                return (
                  <Step key={label} {...stepProps}>
                    <StepLabel {...labelProps}>{label}</StepLabel>
                  </Step>
                );
              })}
            </Stepper>
            {activeStep === steps.length ? (
              <React.Fragment>
              </React.Fragment>
            ) : (
              <React.Fragment>

                <div>
                  {step == 2 ? <Dilivery /> : <Ordersummary />}
                </div>
              </React.Fragment>
            )}
          </Box>
        </div>
      </main>
    </>
  );
}
