import Head from "next/head";
import { gsap } from "gsap/dist/gsap";
import { useEffect, useLayoutEffect, useRef } from "react";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import acsry from '../assets/acsry.jpg'
import wfshn from '../assets/wfshn.jpg'
import mfshn from '../assets/mfshn.jpg'

export default function Home() {
  const root = useRef();
  const page0 = useRef();

  useEffect(() => {
    if (page0.current) {
      setTimeout(() => {
        page0.current.style.top = '-150%';
      }, 2000);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Veloura</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/veloura.png" />
      </Head>
      <main className={styles.main} ref={root}>
      <div className={styles.page0} ref={page0}>
        <div className={styles.page0side} style={{width:'30vw',backgroundColor:'white',overflow:"hidden"}}>
          <h1><span style={{color:'black'}}>V</span>ELOURA</h1>
          <h1>V<span style={{color:'black'}}>E</span>LOURA</h1>
          <h1>VE<span style={{color:'black'}}>L</span>OURA</h1>
          <h1>VEL<span style={{color:'black'}}>O</span>URA</h1>
          <h1>VELO<span style={{color:'black'}}>U</span>RA</h1>
          <h1>VELOU<span style={{color:'black'}}>R</span>A</h1>
          <h1>VELOUR<span style={{color:'black'}}>A</span></h1>
          <h1><span style={{color:'black'}}>V</span>ELOURA</h1>
          <h1>V<span style={{color:'black'}}>E</span>LOURA</h1>
          <h1>VE<span style={{color:'black'}}>L</span>OURA</h1>
          <h1>VEL<span style={{color:'black'}}>O</span>URA</h1>
          <h1>VELO<span style={{color:'black'}}>U</span>RA</h1>
          <h1>VELOU<span style={{color:'black'}}>R</span>A</h1>
          <h1>VELOUR<span style={{color:'black'}}>A</span></h1>
        </div>
        <div className={styles.page0right}>
        <img src="/circle.jpg" alt="img" />
        <h1>VELOURA</h1>
        <button>Click to Enter</button>
        </div>
      </div>
        <div className={styles.page1}>
          <div className={styles.textheading}>
            <h2>Introducing the Latest Styles</h2>
            <h1>
              Discover the 2023 <br />
              <span
                style={{
                  color: "transparent",
                  WebkitTextStroke: "1px white",
                  fontSize: "4.2rem",
                }}
              >
                Fall-Winter
              </span>{" "}
              Collection
            </h1>
            <h3>
              A dedicated brand curating premium essentials. <br />
              Crafted with a strong commitment to ethical practices and an
              uncompromising focus on superior quality.
            </h3>
            <a className="shopnow" href="">
              SHOP NOW
            </a>
          </div>
          <div className={styles.videopage}>
            <video autoPlay loop muted playsInline src="/video1.mp4"></video>
          </div>
        </div>

        <div className={styles.page2}>
          <div style={{display:'flex'}}>
            <div style={{overflow:'hidden'}}><Image style={{border:"1px solid #CCCCCC"}} src={wfshn}/></div>
            <div style={{width:"20vw", display:"flex",flexDirection:"column",justifyContent:"center",paddingLeft:'1rem'}}>
              <a href="">Womens Clothing</a>
              <h2>Graceful Glamour, <br />Your Go-To Destination for Women's Apparel</h2>
            </div>
          </div>
          <div style={{display:'flex'}}>
          <div style={{overflow:'hidden'}}><Image style={{border:"1px solid #CCCCCC"}} src={mfshn} /></div>
          <div style={{width:"20vw", display:"flex",flexDirection:"column",justifyContent:"center",paddingLeft:'1rem'}}>
              <a href="">Mens Clothing</a>
              <h2>Modern Gents, Classic Threads, Upgrade Your Wardrobe Now</h2>
            </div>
          </div>
          <div style={{display:'flex'}}>
          <div style={{overflow:'hidden'}}><Image style={{border:"1px solid #CCCCCC"}} src={acsry} /></div>
          <div style={{width:"20vw", display:"flex",flexDirection:"column",justifyContent:"center",paddingLeft:'1rem'}}>
              <a href="">Accessories</a>
              <h2>Beyond the Ordinary, Accessories that Speak Volumes</h2>
            </div>
          </div>
        </div>

      </main>
    </>
  );
}
