import Head from 'next/head'
import React, { useRef, useState, useEffect } from 'react'
import styles from "@/styles/Home.module.css";

const productpage = () => {
    return (
        <>
            <Head>
                <title>product page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/veloura.png" />
            </Head>
            <main>
                <div className={styles.pmain}>
                    <img src="https://lenouveauchef.com/cdn/shop/files/908001069_5-full-front.jpg?v=1708623938&width=1440" alt="" />
                    <div>
                        <div>Product Name <span style={{marginLeft:'8rem'}}>Rs.16,000.00</span></div>
                        <h2>Product category</h2>
                        <div className={styles.colours}>
                            <span><div className={styles.clbtn} style={{backgroundColor:'blue'}}></div></span>
                            <span><div className={styles.clbtn} style={{backgroundColor:'grey'}}></div></span>
                            <span><div className={styles.clbtn} style={{backgroundColor:'purple'}}></div></span>
                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}

export default productpage