import Head from 'next/head'
import React, { useRef, useState, useEffect } from 'react'
import styles from "@/styles/Home.module.css";

const Shop = () => {

    return (
        <>
            <Head>
                <title>Shop</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/veloura.png" />
            </Head>
            <main className={styles.shop}>
                <div className={styles.filter}>
                <h1>Men's Clothing</h1>
                <p>Filters</p>
                
                    
                </div>

                <div style={{ display: 'flex', flexWrap: 'wrap', margin: '0 auto', justifyContent: 'space-evenly' }}>
                    <div style={{ margin: '1rem 0rem' }}>
                        <img style={{ width: '250px' }} src="//lenouveauchef.com/cdn/shop/files/101200086_5-full-front.jpg?v=1698245764" alt="image" />
                        <div style={{ padding: '0.5rem 1rem' }}>
                            <p style={{ color: '#1F2937', letterSpacing: '0.5px', fontWeight: '450', fontSize: '0.9rem' }}>Jacket Chavi grey</p>
                            <p style={{ color: '#85888A', letterSpacing: '0.5px', fontWeight: '450', fontSize: '0.9rem' }}>Rs. 18000.00</p>
                            <p><small>2 colors +</small></p>
                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}

export default Shop;
